language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - 7.1

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install
